package database

type Post struct {
	ID        string
	Content   string
	IsVisible bool
	Rating    int
	Tags      []string
}

var Posts = []Post{
	{
		ID:        "640c8202f83bd8ff91366419",
		Content:   "Elit voluptate voluptate aute aliqua anim. Anim sunt commodo eiusmod aliquip cillum officia enim excepteur cillum esse proident ipsum et nostrud. Proident officia anim eu eu duis. Labore irure veniam dolor est. Nisi eu adipisicing eiusmod nostrud cillum incididunt quis do adipisicing non aliqua qui occaecat. Nulla nostrud anim sint consectetur officia.\r\n",
		IsVisible: false,
		Rating:    2,
		Tags: []string{
			"enim",
			"veniam",
			"do",
			"laborum",
			"aliquip",
			"mollit",
			"mollit",
		},
	},
	{
		ID:        "640c8202082da36601b1adfe",
		Content:   "Voluptate ex dolor in cillum. Sit veniam et ad est nisi mollit sit. Id cillum et aliqua id. Eiusmod amet eu sint mollit nostrud amet id proident ea pariatur. Nostrud Lorem magna nostrud anim.\r\n",
		IsVisible: false,
		Rating:    3,
		Tags: []string{
			"nisi",
			"sit",
			"duis",
			"nostrud",
			"eiusmod",
			"nostrud",
			"ut",
		},
	},
	{
		ID:        "640c8202580160bffc4d0a74",
		Content:   "In cupidatat qui ex nostrud deserunt non consequat irure. Amet consectetur aute cupidatat officia quis non. Nostrud fugiat cupidatat quis eiusmod do enim eiusmod deserunt dolore ea est.\r\n",
		IsVisible: false,
		Rating:    1,
		Tags: []string{
			"aliqua",
			"sit",
			"non",
			"qui",
			"ipsum",
			"aliqua",
			"commodo",
		},
	},
	{
		ID:        "640c82023446931eb8f2390c",
		Content:   "Incididunt sit et tempor non sit qui culpa nulla ut veniam culpa sit incididunt id. Quis et aliquip commodo fugiat exercitation laborum commodo cillum ea. Fugiat aliqua laborum dolore culpa velit fugiat eu.\r\n",
		IsVisible: true,
		Rating:    2,
		Tags: []string{
			"ad",
			"veniam",
			"ut",
			"amet",
			"adipisicing",
			"cupidatat",
			"ex",
		},
	},
	{
		ID:        "640c8202f0d66b32b286f120",
		Content:   "Est fugiat proident amet consequat proident consectetur consectetur. Et tempor aliqua minim aute nostrud aliqua ad ad irure duis id. Irure adipisicing dolor laborum cillum ipsum non adipisicing fugiat fugiat commodo. In enim aliqua non elit. Voluptate qui magna eiusmod ut dolore enim reprehenderit ea nisi. Labore ut dolor nulla enim ullamco irure enim sit Lorem in sint quis cupidatat irure. Quis consectetur ut laborum enim eu eu qui nostrud veniam dolore fugiat excepteur.\r\n",
		IsVisible: true,
		Rating:    3,
		Tags: []string{
			"magna",
			"labore",
			"minim",
			"reprehenderit",
			"consequat",
			"sunt",
			"aute",
		},
	},
	{
		ID:        "640c82021146154f10b362d8",
		Content:   "Ullamco consequat eiusmod est eu proident non. Sint veniam anim qui consectetur dolor laboris consequat nisi ea do amet. Nulla proident quis mollit laborum exercitation qui sit consequat deserunt amet. Excepteur adipisicing aliquip anim minim qui tempor.\r\n",
		IsVisible: true,
		Rating:    3,
		Tags: []string{
			"ex",
			"non",
			"veniam",
			"non",
			"non",
			"excepteur",
			"aliquip",
		},
	},
	{
		ID:        "640c82027e5eea06e63e6c8c",
		Content:   "Deserunt nisi ullamco reprehenderit et sint sunt aliquip. Velit esse Lorem occaecat commodo laboris id nulla. Esse ex ullamco officia ad duis ea aute ad culpa reprehenderit Lorem eiusmod. Nostrud reprehenderit consectetur incididunt mollit qui adipisicing incididunt elit commodo amet.\r\n",
		IsVisible: true,
		Rating:    0,
		Tags: []string{
			"non",
			"occaecat",
			"esse",
			"elit",
			"pariatur",
			"deserunt",
			"occaecat",
		},
	},
	{
		ID:        "640c8202d09c04e243eb1c80",
		Content:   "Dolore adipisicing proident labore tempor pariatur adipisicing minim labore proident cillum ut occaecat. Nostrud do duis duis occaecat cillum aliqua mollit eu fugiat. Est est voluptate dolore non ex ea. Est pariatur minim occaecat ipsum est aute commodo mollit commodo ex amet amet sit. Ipsum sit amet sint culpa do deserunt exercitation est excepteur non dolor incididunt reprehenderit. Irure ipsum sint nostrud id nostrud nisi anim laborum proident. Lorem non excepteur nostrud laboris esse aliqua ut id proident excepteur nulla commodo.\r\n",
		IsVisible: false,
		Rating:    0,
		Tags: []string{
			"Lorem",
			"nostrud",
			"incididunt",
			"fugiat",
			"cillum",
			"duis",
			"anim",
		},
	},
	{
		ID:        "640c8202244eb0588aeac0a3",
		Content:   "Sunt elit labore sint mollit anim qui aliquip nostrud occaecat duis pariatur aute. Voluptate laboris labore quis ipsum et laborum ea cillum est ea ex. Aliquip voluptate proident aute esse occaecat anim non esse Lorem deserunt. Amet ut quis laboris dolore quis culpa veniam aute exercitation aliqua nulla velit duis. Aute in eiusmod adipisicing nisi. Cupidatat quis ex nulla dolore consectetur incididunt id mollit ullamco sint. Aliqua officia aliquip dolore consectetur ut consectetur fugiat pariatur ex exercitation duis cupidatat excepteur.\r\n",
		IsVisible: false,
		Rating:    3,
		Tags: []string{
			"esse",
			"ex",
			"enim",
			"eu",
			"ut",
			"mollit",
			"occaecat",
		},
	},
	{
		ID:        "640c820207555e7a44e3c27b",
		Content:   "Consectetur non non duis ut eu velit labore. Et cupidatat dolore Lorem deserunt dolore proident exercitation. Est incididunt magna incididunt do voluptate laboris ullamco sunt anim in cupidatat.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"sint",
			"excepteur",
			"occaecat",
			"in",
			"nisi",
			"duis",
			"minim",
		},
	},
	{
		ID:        "640c82024fd39209a7da70b8",
		Content:   "Fugiat est ullamco consequat id quis laborum magna. Quis occaecat amet id cillum exercitation magna et occaecat est aute magna. Aliqua cupidatat quis commodo consequat et magna nulla quis veniam labore. Anim enim eiusmod labore deserunt ipsum eu. Ipsum in elit ipsum id eiusmod elit qui.\r\n",
		IsVisible: true,
		Rating:    5,
		Tags: []string{
			"commodo",
			"incididunt",
			"dolor",
			"enim",
			"fugiat",
			"nostrud",
			"aliqua",
		},
	},
	{
		ID:        "640c8202c597e889d6e6d58d",
		Content:   "Esse minim nostrud consectetur aliquip occaecat. Non laborum in deserunt ipsum quis duis qui do reprehenderit voluptate elit adipisicing tempor excepteur. Velit nisi amet ea id cupidatat quis magna amet tempor nulla ex aliquip mollit.\r\n",
		IsVisible: false,
		Rating:    5,
		Tags: []string{
			"mollit",
			"aliqua",
			"deserunt",
			"fugiat",
			"mollit",
			"Lorem",
			"ullamco",
		},
	},
	{
		ID:        "640c82029e7c48bbd80b4966",
		Content:   "Sunt voluptate nostrud culpa velit anim sunt adipisicing elit pariatur. Duis velit ipsum labore deserunt minim ad ad sit aliqua cupidatat quis aute. Irure exercitation deserunt et id magna proident officia.\r\n",
		IsVisible: false,
		Rating:    2,
		Tags: []string{
			"ex",
			"cillum",
			"exercitation",
			"do",
			"ipsum",
			"occaecat",
			"ullamco",
		},
	},
	{
		ID:        "640c820269880d7bb826e67d",
		Content:   "Qui qui sunt reprehenderit non qui. Excepteur exercitation duis et voluptate dolore cillum ullamco ut ea laboris ea aliquip dolore velit. Sint aute anim exercitation commodo excepteur aliqua cupidatat cupidatat fugiat veniam mollit in. Ex aliqua et mollit laboris ipsum ullamco.\r\n",
		IsVisible: true,
		Rating:    0,
		Tags: []string{
			"reprehenderit",
			"occaecat",
			"qui",
			"dolor",
			"ea",
			"ipsum",
			"sit",
		},
	},
	{
		ID:        "640c8202a04834ba847843d4",
		Content:   "Occaecat aute enim esse eiusmod exercitation laborum id nulla. Nulla do mollit officia labore aliqua. Ex ad laboris adipisicing non do magna. Lorem ad minim irure consequat laborum laborum amet incididunt dolore quis duis irure cupidatat.\r\n",
		IsVisible: false,
		Rating:    5,
		Tags: []string{
			"ullamco",
			"labore",
			"duis",
			"eu",
			"id",
			"commodo",
			"laboris",
		},
	},
	{
		ID:        "640c8202fb1cbc3b5d769781",
		Content:   "Minim est elit tempor nulla nulla. Est est culpa eiusmod aliquip dolor eiusmod quis tempor laboris magna id aliquip. Eu ut qui laborum labore laborum laboris incididunt est cupidatat sunt laboris aute officia excepteur. In ut proident cillum sunt non minim ea et est duis veniam velit non. Id cillum voluptate eiusmod velit fugiat irure non aute fugiat.\r\n",
		IsVisible: false,
		Rating:    5,
		Tags: []string{
			"excepteur",
			"Lorem",
			"pariatur",
			"in",
			"aute",
			"aute",
			"do",
		},
	},
	{
		ID:        "640c8202b61fe97df353d30d",
		Content:   "Officia excepteur quis commodo laborum ullamco nostrud ut laborum dolore aliqua. Aute deserunt nisi tempor quis ut non. Ut culpa culpa commodo laboris deserunt occaecat ex voluptate nisi sint. Laborum laboris irure cillum enim quis commodo.\r\n",
		IsVisible: true,
		Rating:    1,
		Tags: []string{
			"ad",
			"nulla",
			"aute",
			"elit",
			"cupidatat",
			"ut",
			"ullamco",
		},
	},
	{
		ID:        "640c8202fe141c646f73b82a",
		Content:   "Consequat officia non ipsum do minim enim cupidatat. Ea sit excepteur aute adipisicing qui sunt velit amet pariatur labore consequat. Est occaecat fugiat esse aute exercitation tempor dolor esse laborum labore. Voluptate pariatur est est amet ipsum voluptate duis occaecat nulla ipsum reprehenderit sunt. Excepteur proident occaecat culpa aliqua qui.\r\n",
		IsVisible: false,
		Rating:    4,
		Tags: []string{
			"officia",
			"mollit",
			"nostrud",
			"ad",
			"veniam",
			"ea",
			"aliqua",
		},
	},
	{
		ID:        "640c820252522b5bfb789fd2",
		Content:   "Anim veniam in aliquip eiusmod anim voluptate dolore dolore sunt mollit id aliqua. Qui eu irure id Lorem id. Minim sunt incididunt velit labore est.\r\n",
		IsVisible: false,
		Rating:    3,
		Tags: []string{
			"est",
			"sit",
			"duis",
			"do",
			"laboris",
			"proident",
			"eu",
		},
	},
	{
		ID:        "640c820261a3542a3d0e913f",
		Content:   "Velit cupidatat ad aute ullamco irure ea aliquip commodo duis labore. Eiusmod qui qui irure proident elit aliqua sunt fugiat nostrud do magna irure aliquip qui. Enim nostrud fugiat voluptate ipsum dolore.\r\n",
		IsVisible: true,
		Rating:    5,
		Tags: []string{
			"minim",
			"laborum",
			"minim",
			"enim",
			"pariatur",
			"consequat",
			"aliquip",
		},
	},
	{
		ID:        "640c8202b15c83342f754337",
		Content:   "Deserunt aute Lorem proident ex qui occaecat consectetur aliquip Lorem aute proident sint adipisicing. In deserunt officia quis ut. Do culpa dolor ex exercitation adipisicing dolore Lorem amet do culpa. Reprehenderit consequat eiusmod veniam sunt elit proident. Ipsum in dolore esse proident dolore exercitation. Sint sunt officia id cupidatat incididunt nisi.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"elit",
			"tempor",
			"Lorem",
			"anim",
			"minim",
			"commodo",
			"reprehenderit",
		},
	},
	{
		ID:        "640c8202abbd38669855ee30",
		Content:   "Ex nostrud amet velit fugiat magna mollit consectetur qui laboris duis. Magna occaecat incididunt eiusmod cillum excepteur ipsum tempor minim eiusmod qui consectetur mollit enim do. Ipsum ut fugiat deserunt id dolore id ex non cillum tempor est. Non tempor amet fugiat reprehenderit. Ullamco tempor labore laborum ea dolore nostrud pariatur fugiat non et adipisicing eu et amet.\r\n",
		IsVisible: true,
		Rating:    2,
		Tags: []string{
			"culpa",
			"veniam",
			"do",
			"dolore",
			"et",
			"deserunt",
			"mollit",
		},
	},
	{
		ID:        "640c8202972a1e5f417bc1ed",
		Content:   "Cupidatat do labore sint in deserunt excepteur sunt voluptate ea consectetur. Commodo officia veniam commodo do anim dolor velit magna irure. Velit qui laborum proident veniam ipsum aliqua occaecat est culpa ut. Ipsum ullamco reprehenderit in pariatur irure irure ad cillum labore. Nulla minim culpa tempor nisi laboris.\r\n",
		IsVisible: true,
		Rating:    1,
		Tags: []string{
			"tempor",
			"non",
			"non",
			"reprehenderit",
			"incididunt",
			"duis",
			"ipsum",
		},
	},
	{
		ID:        "640c82021ae84be42e41e661",
		Content:   "Commodo ullamco fugiat do anim nisi duis enim qui id ea est anim laborum aliqua. Anim consectetur ex ad laborum fugiat laboris pariatur fugiat mollit ea anim. Ex culpa anim proident ea elit commodo aliqua fugiat mollit. Eiusmod et eiusmod tempor veniam eiusmod non ipsum. Do ipsum dolor aute ullamco consectetur dolore proident ex ex. Esse sit ea mollit aute laboris cillum.\r\n",
		IsVisible: false,
		Rating:    2,
		Tags: []string{
			"esse",
			"enim",
			"mollit",
			"reprehenderit",
			"in",
			"et",
			"officia",
		},
	},
	{
		ID:        "640c820287ab7dafbde84c7d",
		Content:   "Excepteur culpa consequat commodo cupidatat culpa magna mollit non. Laboris fugiat irure mollit quis velit duis. Tempor nostrud laboris tempor do nulla eu.\r\n",
		IsVisible: true,
		Rating:    1,
		Tags: []string{
			"anim",
			"culpa",
			"aliquip",
			"aliquip",
			"aute",
			"veniam",
			"ut",
		},
	},
	{
		ID:        "640c82023f739bc78f935cb8",
		Content:   "Reprehenderit dolore esse excepteur pariatur excepteur Lorem irure aliquip cupidatat sit laboris deserunt ipsum aute. Minim excepteur occaecat aliquip nulla ullamco cupidatat veniam non commodo ad exercitation nulla qui non. Irure minim sint reprehenderit et cupidatat exercitation tempor. Proident consectetur non aute reprehenderit aute eiusmod do exercitation minim minim aliqua. Et fugiat ea in proident ea nulla laboris. In id ad anim ullamco nulla anim do adipisicing id duis irure in adipisicing quis. Laboris cupidatat est dolore consectetur.\r\n",
		IsVisible: true,
		Rating:    1,
		Tags: []string{
			"deserunt",
			"nostrud",
			"dolore",
			"mollit",
			"est",
			"esse",
			"occaecat",
		},
	},
	{
		ID:        "640c8202cadee5699a7c305d",
		Content:   "Deserunt aliquip non nisi enim duis ipsum fugiat anim. Quis laboris est sint quis eu officia excepteur anim voluptate proident anim deserunt enim. Amet do sint enim commodo sit enim ut consequat commodo mollit mollit. Sit occaecat ut esse cillum duis fugiat laboris ea commodo minim aliqua laboris officia labore. Ea quis commodo nulla sint aliquip fugiat culpa id ad magna. Est laborum do cupidatat occaecat.\r\n",
		IsVisible: true,
		Rating:    5,
		Tags: []string{
			"Lorem",
			"mollit",
			"duis",
			"eiusmod",
			"do",
			"consectetur",
			"ad",
		},
	},
	{
		ID:        "640c820212a1ed86f5aad55a",
		Content:   "Consequat officia ullamco commodo ipsum anim. Duis voluptate laborum do reprehenderit consectetur dolore. Incididunt est qui ex aliqua est est enim anim commodo Lorem consequat. Fugiat occaecat est cupidatat non velit Lorem occaecat. Officia ut aliqua elit ut adipisicing reprehenderit voluptate consectetur magna aliqua dolor. Tempor magna non do sint sint laborum laborum eiusmod qui eiusmod non officia. Aliquip Lorem culpa adipisicing enim irure velit est quis id elit eiusmod officia.\r\n",
		IsVisible: true,
		Rating:    2,
		Tags: []string{
			"esse",
			"pariatur",
			"id",
			"do",
			"veniam",
			"aute",
			"eu",
		},
	},
	{
		ID:        "640c82023a0aa100e9c65c0b",
		Content:   "Est eiusmod aliquip voluptate duis tempor duis mollit et sit exercitation dolore aliquip. Exercitation eiusmod ut anim sint est qui adipisicing. Do amet non cillum deserunt magna et labore amet adipisicing veniam aute mollit id consequat. Amet enim laborum magna ea adipisicing nisi duis amet non non tempor exercitation. Quis quis velit ipsum aliquip commodo proident sit aute nostrud pariatur.\r\n",
		IsVisible: true,
		Rating:    2,
		Tags: []string{
			"cillum",
			"officia",
			"pariatur",
			"quis",
			"nulla",
			"duis",
			"dolor",
		},
	},
	{
		ID:        "640c820283ab034bc3b7ba24",
		Content:   "Minim deserunt irure nostrud esse non nisi commodo anim amet amet labore ut. Incididunt nulla ullamco velit fugiat. Velit cillum nulla velit elit sunt quis. Qui nisi duis sunt Lorem amet adipisicing veniam sit commodo officia dolor sit. Est culpa et voluptate ex dolor esse anim. Eiusmod aliquip fugiat Lorem ullamco sit amet incididunt culpa velit velit cillum irure.\r\n",
		IsVisible: false,
		Rating:    4,
		Tags: []string{
			"commodo",
			"elit",
			"aliqua",
			"non",
			"eiusmod",
			"consectetur",
			"et",
		},
	},
	{
		ID:        "640c8202dba677b64e781b59",
		Content:   "Duis qui tempor nisi sint culpa dolore. Deserunt consequat officia amet magna voluptate velit quis culpa laborum. Magna proident quis id deserunt cupidatat excepteur. Amet sint cupidatat sit ex eiusmod ut magna irure nulla ullamco veniam exercitation. Fugiat ad exercitation aliquip velit fugiat nulla nulla consectetur. Est cupidatat et ipsum minim sunt cillum. Amet consequat voluptate commodo minim anim ullamco voluptate incididunt pariatur.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"labore",
			"adipisicing",
			"minim",
			"commodo",
			"labore",
			"irure",
			"aliquip",
		},
	},
	{
		ID:        "640c8202c9f13a233e35de8e",
		Content:   "Aliquip culpa ex minim anim. Ex ipsum cupidatat voluptate exercitation ea labore irure irure id irure cillum. Aliqua occaecat consequat esse irure ipsum fugiat aliqua aliqua commodo. Fugiat enim minim sunt dolore est.\r\n",
		IsVisible: false,
		Rating:    0,
		Tags: []string{
			"consectetur",
			"nostrud",
			"officia",
			"veniam",
			"reprehenderit",
			"excepteur",
			"culpa",
		},
	},
	{
		ID:        "640c82024de0dc670777887c",
		Content:   "Voluptate ad in laboris sunt. Aute enim dolore laboris nisi minim minim Lorem cillum laboris sunt pariatur excepteur. Officia enim eiusmod tempor qui dolor cupidatat. Culpa amet minim sit exercitation irure labore velit tempor ad eu adipisicing et laborum ea. Mollit pariatur est sint esse cillum consectetur cillum. Sint non adipisicing reprehenderit ipsum consequat ut. Irure minim consectetur minim aliqua sunt laboris officia officia laborum deserunt aliquip officia esse voluptate.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"adipisicing",
			"sint",
			"adipisicing",
			"sunt",
			"culpa",
			"qui",
			"ut",
		},
	},
	{
		ID:        "640c82023893f992e3e319f9",
		Content:   "Duis incididunt reprehenderit incididunt duis eiusmod magna eu laborum et fugiat. Laboris laborum proident elit nisi commodo exercitation aliqua esse. Ullamco Lorem in id cillum aliqua velit culpa. Ullamco do anim excepteur incididunt adipisicing commodo id proident nulla ut occaecat excepteur. Esse enim cillum cupidatat reprehenderit id culpa laborum incididunt fugiat duis id ad.\r\n",
		IsVisible: false,
		Rating:    3,
		Tags: []string{
			"aliqua",
			"cillum",
			"aute",
			"esse",
			"fugiat",
			"excepteur",
			"quis",
		},
	},
	{
		ID:        "640c82025038d63a0083eb56",
		Content:   "Et adipisicing non velit nisi laboris elit eiusmod adipisicing culpa id. Aliquip nisi proident velit proident. Mollit irure consequat voluptate fugiat eiusmod eiusmod ea mollit deserunt commodo magna Lorem sit. Laboris aute deserunt mollit velit duis.\r\n",
		IsVisible: true,
		Rating:    1,
		Tags: []string{
			"amet",
			"officia",
			"culpa",
			"culpa",
			"in",
			"sint",
			"duis",
		},
	},
	{
		ID:        "640c8202e04995105d999be3",
		Content:   "Non officia aliquip ullamco ut sint ipsum laboris ut mollit velit irure labore. Cupidatat do sunt minim duis. Nostrud sit est nulla officia nisi reprehenderit tempor id labore consequat officia.\r\n",
		IsVisible: false,
		Rating:    0,
		Tags: []string{
			"duis",
			"minim",
			"excepteur",
			"commodo",
			"nisi",
			"quis",
			"ea",
		},
	},
	{
		ID:        "640c820268cca2f33b68093b",
		Content:   "In veniam in sint enim ad laborum velit ad laborum amet commodo quis. Laboris ipsum amet eiusmod non occaecat duis quis esse quis Lorem incididunt cupidatat. Velit deserunt non eiusmod cillum esse deserunt elit ut officia. Officia sint sit esse ex nisi et eu do ea occaecat eu adipisicing nulla. Commodo ex est dolore deserunt qui.\r\n",
		IsVisible: false,
		Rating:    3,
		Tags: []string{
			"et",
			"laborum",
			"incididunt",
			"labore",
			"minim",
			"enim",
			"velit",
		},
	},
	{
		ID:        "640c8202622406f0e6635bad",
		Content:   "Minim id incididunt cillum incididunt ipsum minim laboris esse dolore nostrud. Laborum in consectetur laboris velit ex pariatur. Voluptate do cillum dolor nostrud ex aute aliquip. Cillum esse eiusmod in labore laborum cillum cillum occaecat pariatur tempor. Pariatur consequat adipisicing ipsum sunt quis ipsum laboris anim enim ut. Consectetur irure nulla aute et elit reprehenderit amet consequat nisi consectetur. Id dolor aliquip velit elit.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"consectetur",
			"incididunt",
			"nostrud",
			"dolore",
			"quis",
			"in",
			"cupidatat",
		},
	},
	{
		ID:        "640c82023253addf6915a886",
		Content:   "Culpa nostrud cillum esse nisi proident labore. Reprehenderit aute minim deserunt fugiat duis tempor dolor laborum id adipisicing voluptate elit. In laboris culpa eu sint ea mollit consequat nulla. Ipsum cupidatat eu amet culpa ipsum consequat eiusmod minim quis.\r\n",
		IsVisible: true,
		Rating:    5,
		Tags: []string{
			"consectetur",
			"laboris",
			"duis",
			"proident",
			"adipisicing",
			"aute",
			"anim",
		},
	},
	{
		ID:        "640c8202f8db9d657d209ea7",
		Content:   "Aliqua laborum irure incididunt sunt eu commodo officia esse ea non irure. Sint nisi proident tempor ullamco qui non in consectetur Lorem. Aliquip nisi laborum eiusmod est quis non elit dolore deserunt. Irure nisi labore amet occaecat aute ipsum ea est. Nisi duis esse qui id deserunt elit pariatur fugiat fugiat laboris eiusmod mollit ullamco non. Culpa anim duis quis ex dolore enim Lorem magna nostrud minim nulla. Fugiat non incididunt esse esse anim anim minim cillum eiusmod aliqua exercitation est amet labore.\r\n",
		IsVisible: true,
		Rating:    3,
		Tags: []string{
			"cillum",
			"cillum",
			"voluptate",
			"officia",
			"labore",
			"excepteur",
			"labore",
		},
	},
	{
		ID:        "640c8202487098e882dc2c5b",
		Content:   "Ex excepteur anim sint irure. Incididunt tempor exercitation eu exercitation fugiat cupidatat fugiat elit mollit. Laboris enim ea excepteur sunt aute est. Reprehenderit duis do sit eu dolor labore reprehenderit deserunt sunt fugiat veniam. Consequat cupidatat ipsum exercitation ipsum nisi velit ad laboris laborum nostrud proident. Cupidatat adipisicing sint magna commodo. Enim aliqua dolor minim qui laboris voluptate sint excepteur.\r\n",
		IsVisible: false,
		Rating:    0,
		Tags: []string{
			"qui",
			"ea",
			"id",
			"nulla",
			"quis",
			"occaecat",
			"ullamco",
		},
	},
	{
		ID:        "640c820262c85aa9548c1f48",
		Content:   "Fugiat nostrud anim ut ut sit laborum excepteur culpa sit eu. Esse labore consequat eiusmod aliqua. Fugiat esse voluptate eiusmod et exercitation minim in eiusmod aute minim velit dolor culpa incididunt. Lorem enim laboris id velit cillum incididunt pariatur magna duis aliqua enim consequat laboris adipisicing.\r\n",
		IsVisible: false,
		Rating:    5,
		Tags: []string{
			"mollit",
			"laboris",
			"cupidatat",
			"enim",
			"veniam",
			"veniam",
			"aute",
		},
	},
	{
		ID:        "640c8202fe6fe7d714f164b2",
		Content:   "Do consectetur officia anim esse mollit sunt laborum et qui ex reprehenderit laboris tempor. Est mollit pariatur cillum pariatur incididunt mollit sint Lorem consectetur voluptate reprehenderit. Non veniam qui magna sint consequat nisi consectetur tempor. Duis cillum incididunt laborum ipsum incididunt irure aute duis amet incididunt fugiat occaecat mollit. Aute et ea irure cupidatat nisi duis est. Aliquip elit nulla duis cupidatat pariatur quis ut pariatur sit. Commodo occaecat culpa consectetur in ea enim reprehenderit.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"dolor",
			"nulla",
			"dolor",
			"fugiat",
			"aliqua",
			"amet",
			"id",
		},
	},
	{
		ID:        "640c820207ad189b3e1cfc43",
		Content:   "Quis pariatur nisi eiusmod elit ad consequat quis fugiat elit commodo ut aliqua. Amet consequat commodo amet ullamco duis ea cillum eu est anim aliquip. Consequat et fugiat esse dolore cupidatat nisi consectetur in consectetur. Irure anim elit minim amet consectetur cupidatat laborum esse veniam fugiat adipisicing incididunt cupidatat.\r\n",
		IsVisible: true,
		Rating:    0,
		Tags: []string{
			"irure",
			"proident",
			"labore",
			"mollit",
			"est",
			"elit",
			"sit",
		},
	},
	{
		ID:        "640c8202b33e648bb2facf5f",
		Content:   "Exercitation magna sint officia excepteur sit ad dolor ad occaecat duis cupidatat non in. Sunt aliquip dolore ut non nostrud eiusmod ipsum. Commodo voluptate eu mollit ea ea labore. Minim reprehenderit ad excepteur adipisicing tempor. Ipsum veniam aliqua cupidatat ut irure proident enim. Culpa enim elit esse minim laborum amet. Elit nostrud cupidatat adipisicing irure laborum veniam.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"fugiat",
			"aute",
			"amet",
			"veniam",
			"irure",
			"pariatur",
			"occaecat",
		},
	},
	{
		ID:        "640c82025e4cac44026daab3",
		Content:   "Velit duis sunt incididunt ad aute consectetur aliqua deserunt anim nulla sunt. Nisi ad tempor commodo aliquip qui. Do anim pariatur elit est pariatur ex fugiat. Quis ad reprehenderit culpa elit culpa nisi tempor.\r\n",
		IsVisible: true,
		Rating:    3,
		Tags: []string{
			"cillum",
			"culpa",
			"nulla",
			"ad",
			"est",
			"incididunt",
			"tempor",
		},
	},
	{
		ID:        "640c8202816d31a4a8584293",
		Content:   "Esse ea eu nulla cillum labore. Incididunt labore ad deserunt aute eu sint sunt occaecat quis. Elit eu sunt occaecat ullamco proident laboris. Occaecat quis deserunt nulla irure adipisicing aute aliqua elit excepteur consectetur ex laboris. Ex tempor cupidatat tempor ullamco veniam voluptate id.\r\n",
		IsVisible: false,
		Rating:    5,
		Tags: []string{
			"ipsum",
			"adipisicing",
			"mollit",
			"sint",
			"officia",
			"fugiat",
			"deserunt",
		},
	},
	{
		ID:        "640c82020d551371c59e2e11",
		Content:   "Cillum consectetur reprehenderit magna non ipsum dolore elit est dolor. Incididunt deserunt amet consectetur laborum in sit consectetur eiusmod nisi reprehenderit laboris ipsum qui. Id laborum do aliquip enim laborum mollit ut anim in in. Aliqua eu nisi aliqua aute veniam culpa ad et. In velit in cupidatat eu laborum id sit do irure voluptate laborum. Non quis occaecat velit Lorem.\r\n",
		IsVisible: false,
		Rating:    1,
		Tags: []string{
			"tempor",
			"amet",
			"dolor",
			"qui",
			"exercitation",
			"labore",
			"laborum",
		},
	},
	{
		ID:        "640c82029ccfa5b5d859a911",
		Content:   "Mollit mollit aute qui sunt nulla. Deserunt velit tempor officia aliqua sunt laborum anim ullamco commodo proident cillum nulla Lorem ullamco. Pariatur incididunt nulla culpa voluptate tempor consectetur esse anim aliquip dolor duis sit. Cupidatat commodo ut amet eu. Non duis ipsum non pariatur dolor. Minim sit dolor ut amet laboris id tempor fugiat dolor magna.\r\n",
		IsVisible: true,
		Rating:    4,
		Tags: []string{
			"culpa",
			"magna",
			"velit",
			"enim",
			"reprehenderit",
			"eiusmod",
			"sit",
		},
	},
	{
		ID:        "640c82027a8a463a1e36454c",
		Content:   "Veniam consequat pariatur incididunt esse laborum tempor veniam aute. Officia voluptate deserunt ipsum est tempor veniam do ullamco officia. Amet eu ut sunt voluptate eiusmod deserunt Lorem do aute proident non occaecat pariatur.\r\n",
		IsVisible: true,
		Rating:    0,
		Tags: []string{
			"tempor",
			"elit",
			"nostrud",
			"incididunt",
			"mollit",
			"tempor",
			"ipsum",
		},
	},
}
